---
title: "Coursera R Programming Assigements "
output: html_notebook
---

Week 2 Assigment 

```{r}
#Load Tidy enviroment 
library("tidyverse")
library("dplyr")
library("stringr")
library("lubridate")
library("knitr")
library("kableExtra")
library("fpp2")
library("readxl")

```

```{r, echo=FALSE}

  # 'directory' is a character vector of length 1 indicating 
  # the name of the pollutant for which we will calculate the mean;       
  # either "sulfate" or "nitrate".
  
  #'id` is an integer vector indicating the monitor ID numbers 
  # to be used
  
  # Return the mean of the pollutant accross all monitors list 
  # in the `id` vector (ignoring NA values)
  # Note: do not round the result 
  
  # set up data search path and clear the object each time function is run


  pollutantmean <- function(directory, pollutant, id=1:332) {
  file_data <- 0
  files <- 0
  path <- 0
  path <- paste(getwd(), directory, sep = "/")
  files <-  list.files(path) 
  

  #Loop through files reading all into file_data
  for (i in 1:length(id)) 
    {
    if (i == 1) {
      file_data <- read_csv(paste(path, files[1], sep = "/"))
      } else {
      file_data <- rbind(file_data, read_csv(paste(path, files[i], sep = "/")))
      }
    }
 
  file_output <- file_data[ , c("sulfate", "nitrate")]
  
  return(mean(file_output, na.rm = TRUE ))

  }


pollutantmean("specdata", "nitrate", 1)

# Date	sulfate	nitrate	ID

  directory <- "specdata"
  id <- 1:3
  pollutant <- "sulfate"
  file_data <- 0
  files <- 0
  path <- 0
  path <- paste(getwd(), directory, sep = "/")
  files <-  list.files(path) 
  for (i in 1:length(id)) 
    {
    if (i == 1) {
      file_data <- read_csv(paste(path, files[1], sep = "/"))
      } else {
      file_data <- rbind(file_data, read_csv(paste(path, files[i], sep = "/")))
      }
    }
 
  file_output <- file_data[ , c("sulfate", "nitrate")]

  path
  files
  id
  head(file_data)
  tail(file_data)
  glimpse(file_data)
  view(file_data)
 
```








